// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocqgqczvovizlxazsfum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcWdxY3p2b3Zpemx4YXpzZnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzgzODgsImV4cCI6MjA2MTQxNDM4OH0.Ey6nnUcrOc9SRTRW_0EcbMuQg_o2njqFrwNNovk9bkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);